"""update appointments table

Revision ID: afca6e980f86
Revises: ab8b50c2e33d
Create Date: 2026-07-21 09:58:21.881495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afca6e980f86'
down_revision: Union[str, Sequence[str], None] = 'ab8b50c2e33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('sorumlular', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'sorumlular')
    # ### end Alembic commands ###
