"""create users and projects tables

Revision ID: d6a284a4f882
Revises: 
Create Date: 2026-06-29 12:58:29.025397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a284a4f882'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('oncelik', sa.Integer(), nullable=True),
    sa.Column('aciliyet', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('aksiyon', sa.String(), nullable=False),
    sa.Column('sorumlular', sa.String(), nullable=False),
    sa.Column('ilgili', sa.String(length=50), nullable=True),
    sa.Column('hedef_tarih', sa.Date(), nullable=True),
    sa.Column('durum', sa.Enum('BEKLEMEDE', 'AÇIK', 'DEVAM_EDİYOR', 'TAMAMLANDI', name='projectstatus'), nullable=False),
    sa.Column('beklenen', sa.String(length=30), nullable=True),
    sa.Column('notlar', sa.String(length=100), nullable=True),
    sa.Column('risk', sa.String(length=50), nullable=True),
    sa.Column('guncel_sira', sa.Integer(), nullable=False),
    sa.Column('tamamlanma', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tamamlanma >= 0 AND tamamlanma <= 100', name='check_tamamlanma_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client'), 'projects', ['client'], unique=False)
    op.create_index(op.f('ix_projects_durum'), 'projects', ['durum'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_durum'), table_name='projects')
    op.drop_index(op.f('ix_projects_client'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
