"""create machines table

Revision ID: e17f88b74e48
Revises: c3d4e5f6a7b8
Create Date: 2026-07-16 13:19:01.873797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17f88b74e48'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('ocak', sa.Text(), nullable=False),
    sa.Column('halat_degisim_tarih', sa.Date(), nullable=True),
    sa.Column('halat_boyu', sa.String(length=100), nullable=True),
    sa.Column('tip', sa.Text(), nullable=True),
    sa.Column('bakim', sa.Boolean(), nullable=False),
    sa.Column('bakim_tarih', sa.Date(), nullable=True),
    sa.Column('marka', sa.String(length=30), nullable=True),
    sa.Column('manuel_kod', sa.String(length=60), nullable=True),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_ocak'), 'machines', ['ocak'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_ocak'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
